<?php

    namespace Tests\Mvc\Functional;

    use DOMDocument;
    use Mvc\Controller\HomeController;
    use Mvc\Controller\PostsController;
    use Mvc\Fixtures\AppFixtures;
    use Mvc\Models\PostModel;
    use PHPUnit\Framework\MockObject\Exception;
    use PHPUnit\Framework\TestCase;
    use Symfony\Component\DomCrawler\Crawler;

    class HomeControllerTest extends TestCase {

        public function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub

            // load fixtures
            $this->fixtures = new AppFixtures();
            $this->fixtures->load();
        }

        public function tearDown(): void
        {
            parent::tearDown(); // TODO: Change the autogenerated stub
            $this->fixtures->unload();
        }

        public function assertRegExp(string $pattern, string $string, string $message = ''): void {
            $this->assertMatchesRegularExpression($pattern, $string, $message);
        }
        public function testIndex(): void
        {
            $controller = new HomeController();
            $html = $controller->index();

            // Est-ce que le document HTML contient un titre h1 ? (on utilise une expression régulière)
            $htmlObject = new DOMDocument();
            $htmlObject->loadHTML($html->getContent(), LIBXML_NOERROR);
            $htmlCrawler = new Crawler($htmlObject);

            $this->assertEquals(200, $html->getStatusCode());
            $this->assertEquals(1, $htmlCrawler->filter('h1')->count());
            $this->assertRegExp('/Page d\'accueil/', $htmlCrawler->filter('h1')->text());
        }

        /**
         * @throws Exception
         */
        public function testShowPosts(): void
        {
            // Creation d'un mock de PostModel
            $postModel = $this->createMock(PostModel::class);
            $postModel->method('findAll')->willReturn([
                (new PostModel())->setId(1)->setTitle('Titre 1')->setContent('Contenu 1')->setAuthor('Auteur 1')->setDate('2021-01-01'),
                (new PostModel())->setId(2)->setTitle('Titre 2')->setContent('Contenu 2')->setAuthor('Auteur 2')->setDate('2021-01-02'),
                (new PostModel())->setId(3)->setTitle('Titre 3')->setContent('Contenu 3')->setAuthor('Auteur 3')->setDate('2021-01-03')
            ]);

            // Test du controller avec le mock
            $controller = new PostsController();
            $html = $controller->showPosts($postModel);

            $htmlObject = new DOMDocument();
            $htmlObject->loadHTML($html->getContent(), LIBXML_NOERROR);
            $htmlCrawler = new Crawler($htmlObject);

            $this->assertEquals(200, $html->getStatusCode());
            $this->assertEquals(3, $htmlCrawler->filter('article')->count());
        }

        public function testShowPostsAsync(): void
        {
            $controller = new PostsController();
            $html = $controller->showPostsAsync();

            $htmlObject = new DOMDocument();
            $htmlObject->loadHTML($html->getContent(), LIBXML_NOERROR);
            $htmlCrawler = new Crawler($htmlObject);

            $this->assertEquals(200, $html->getStatusCode());
            $this->assertEquals(1, $htmlCrawler->filter('div')->count());
        }

        public function testShowAddForm(): void
        {
            $controller = new PostsController();
            $html = $controller->showAddForm();

            $htmlObject = new DOMDocument();
            $htmlObject->loadHTML($html->getContent(), LIBXML_NOERROR);
            $htmlCrawler = new Crawler($htmlObject);

            $this->assertEquals(200, $html->getStatusCode());
            $this->assertEquals(1, $htmlCrawler->filter('form')->count());

            // vérification de l'affichage des champs
            $this->assertEquals(1, $htmlCrawler->filter('input[name="title"]')->count());
            $this->assertEquals(1, $htmlCrawler->filter('textarea[name="content"]')->count());
            $this->assertEquals(1, $htmlCrawler->filter('input[name="author"]')->count());
        }

        public function testSubmitFormWithErrors(): void
        {
            $controller = new PostsController();
            $html = $controller->submitAddForm();

            $htmlObject = new DOMDocument();
            $htmlObject->loadHTML($html->getContent(), LIBXML_NOERROR);
            $htmlCrawler = new Crawler($htmlObject);

            $this->assertEquals(400, $html->getStatusCode());
            $this->assertEquals(1, $htmlCrawler->filter('div.alert-danger')->count());
            $this->assertEquals(6, $htmlCrawler->filter('div.alert-danger ul li')->count());
        }

        public function testSubmitWithSuccess(): void
        {
            // Mock méthode redirect
            $controller = $this->getMockBuilder(PostsController::class)
                ->onlyMethods(['redirect'])
                ->getMock();

            // define the $_POST array
            $_POST['title'] = 'Titre';
            $_POST['content'] = 'Contenu';
            $_POST['author'] = 'Auteur';

            // On dit que la méthode submitAddForm de controller doit appeler la méthode redirect
            // avec la route posts à la fin de son traitement
            $controller->expects($this->once())
                ->method('redirect')
                ->with('posts');

            // On appelle la méthode submit pour vérifier cela
            $controller->submitAddForm();
        }
    }