<?php

namespace Mvc\Models;

use Mvc\Fixtures\AppFixtures;
use PHPUnit\Framework\TestCase;

class PostModelTest extends TestCase
{
    private AppFixtures $fixtures;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // load fixtures
        $this->fixtures = new AppFixtures();
        $this->fixtures->load();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->fixtures->unload();
    }

    // test la fonction findAll de PostModel
    public function testFindAll(): void
    {
        $postModel = new PostModel();
        $posts = $postModel->findAll();
        $this->assertCount(5, $posts);
    }

    /**
     * @throws \Exception
     */
    public function testSave(): void
    {
        $postModel = new PostModel();
        $postModel->setTitle('Titre 6');
        $postModel->setContent('Contenu 6');
        $postModel->setAuthor('Auteur 6');
        $postModel->setDate(date('Y-m-d H:i:s'));
        $insertedRow = $postModel->save();
        $this->assertIsInt($insertedRow);

        $posts = $postModel->findAll();
        $this->assertCount(6, $posts);
    }

    /**
     * @throws \Exception
     */
    public function testFailedSave(): void
    {
        $this->expectException(\Exception::class);

        $postModel = new PostModel();
        $postModel->setTitle('Titre 6');
        $postModel->setDate(date('Y-m-d H:i:s'));
        $postModel->save();
    }
}