<?php

namespace Mvc\Models;

use Mvc\Fixtures\AppFixtures;
use PHPUnit\Framework\TestCase;

class PostModelTest extends TestCase
{
    private AppFixtures $fixtures;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // load fixtures
        $this->fixtures = new AppFixtures();
        $this->fixtures->load();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->fixtures->unload();
    }

    // test la fonction findAll de PostModel
    public function testFindAll(): void
    {
        $postModel = new PostModel();
        $posts = $postModel->findAll();
        $this->assertCount(5, $posts);
    }
}