name: CI-composer-version

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl zip sockets dom pdo_mysql

      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'test'
          mysql user: 'user'
          mysql password: 'pass'

      - uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          php_extensions: intl zip sockets dom pdo_mysql

      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version

      - uses: nanasess/setup-chromedriver@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: chromedriver --version

      - name: Load migrations
        run: php command.php migrate

      - name: run tests
        env:
          PANTHER_CHROME_ARGUMENTS: "--disable-dev-shm-usage"
          PANTHER_CHROME_DRIVER_BINARY: "/usr/bin/chromedriver"
          PANTHER_NO_SANDBOX: "1"
          PANTHER_GECKO_DRIVER_BINARY: "/usr/bin/geckodriver"
          PANTHER_GECKO_ARGUMENTS: "--marionette-port=2828"
          DB_TEST_HOST: '127.0.0.1'
          DB_TEST_USERNAME: 'user'
          DB_TEST_PASSWORD: 'pass'
          DB_TEST_NAME: 'test'
        run: vendor/bin/phpunit --colors=always --configuration=phpunit.xml